apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: shard
  namespace: demo
  labels:
    archiver: "true"
spec:
  version: "4.4.26"
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
    mongos:
      replicas: 2
    shard:
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
  terminationPolicy: WipeOut
