apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: linode-secret
  namespace: demo
stringData:
  AWS_ACCESS_KEY_ID: <>
  AWS_SECRET_ACCESS_KEY: <>
  AWS_ENDPOINT: https://us-east-1.linodeobjects.com