apiVersion: archiver.kubedb.com/v1alpha1
kind: PostgresArchiver
metadata:
  name: pg-archiver
  namespace: demo
spec:
  pause: false
  databases:
    namespaces:
      from: Selector
      selector:
        matchLabels:
          kubernetes.io/metadata.name: demo
    selector:
      matchLabels:
        archiver: "true"
  retentionPolicy:
    name: postgres-retention-policy
    namespace: demo
  encryptionSecret:
    name: "encrypt-secret"
    namespace: "demo"
  fullBackup:
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 70
          runAsGroup: 70
          fsGroup: 70
    driver: "VolumeSnapshotter"
    task:
      params:
        volumeSnapshotClassName: "longhorn-vsc" # "gke-vsc" # "az-vsc"  # Set accordingly
    scheduler:
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      schedule: "30 3 * * *"
    sessionHistoryLimit: 3
  manifestBackup:
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 70
          runAsGroup: 70
          fsGroup: 70
    scheduler:
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      schedule: "30 3 * * *"
    sessionHistoryLimit: 3
  backupStorage:
    ref:
      name: "local-storage"
      namespace: "demo"
