apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: storage
  namespace: demo
stringData:
  AWS_ACCESS_KEY_ID: "PKJ********************"
  AWS_SECRET_ACCESS_KEY: "vBGu**********************"
  AWS_ENDPOINT: https://ap-south-1.linodeobjects.com
