apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: storage
  namespace: demo
spec:
  storage:
    provider: local
    local:
      mountPath: /pg/walg
      nfs:
        server: 10.128.38.158:2049
        path: /exports
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false
  deletionPolicy: WipeOut
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
    pod:
      securityContext:
        fsGroup: 70
        runAsUser: 70
        runAsGroup: 70